export const sections = [
  {
    title: "Painting",
    type: "item_view",
    items: [
      {
        title: "As of Nineteen",
        details: [
          "Oil on canvas, oil and paint marker on plywood, 2x4 wood",
          '28" x 20" x 18"',
        ],
        images: ["painting/As of Nineteen/asof19_main1.jpg"],
        processImages: [
          "painting/As of Nineteen/asof19_process1.jpg",
          "painting/As of Nineteen/asof19_process2.jpg",
          "painting/As of Nineteen/asof19_process3.jpg",
          "painting/As of Nineteen/asof19_process4.jpg",
          "painting/As of Nineteen/asof19_process5.jpg",
          "painting/As of Nineteen/asof19_process6.jpg",
          "painting/As of Nineteen/asof19_process7.jpg",
          "painting/As of Nineteen/asof19_process8.jpg",
          "painting/As of Nineteen/asof19_process9.jpg",
        ],
        description: "This is the description for this piece.",
      },
      {
        title: "Calder Study",
        details: ["Oil on canvas", '18" x 24"'],
        images: ["painting/Calder study/CalderStudy_website copy.jpg"],
        processImages: [],
        description: "This is the description for this piece.",
      },
      {
        title: "Self Portrait",
        details: ["Oil on canvas", '12" x 9"'],
        images: ["painting/Self Portrait/IMG_2691 copy.jpg"],
        processImages: [],
        description: "This is the description for this piece.",
      },
      {
        title: "Vanderpoel Color Study",
        details: ["Oil on canvas paper", '18" x 24"'],
        images: ["painting/Color study/colorstudy.JPG"],
        processImages: [],
        description:
          "A study of Emily Noyes Vanderpoel’s Color Problems. Looking at how color interacts within everday objects and if spaciality can be expressed through a simplification of color on a 10 x 10 grid. ",
      },
    ],
  },
  {
    title: "Sewing",
    type: "item_view",
    items: [
      {
        title: "Modular Backpack",
        details: [
          "Design",
          "Material/ Parts Selection",
          "Patterning",
          "Sewing",
        ],
        images: ["sewing/Modular Backpack/MAIN PHOTOS/backpack_1.jpg"],
        processImages: [],
        description: [
          "Designed in accordance with what I believe to be the perfect everyday backpack. The process began with researching my favorite backpacks and then meticulously picking out materials and hardware. I wanted to make a bag that suited all of my needs, would last for years, and was modular. The modularity is key in making it last since it allows the pocket designs to be changed at any point.",
          "",
          "About 30 separate components patterned by hand.",
          "",
          "Padded laptop/ notebook compartment; main compartment with divider organizer; shock cord front panel (for quick access); removable front pouches (turns into side bag).",
        ],
      },
      {
        title: "Three Pant Work Jacket",
        details: ["Design", "Material/ Parts Selection", "Sewing"],
        processImages: [],
        images: ["sewing/Three Pant Work Jacket/three_pant_WJ_main.jpg"],
        description:
          "This jacket is made out of three different pairs of pants I had lying around the house. The color and wash on all three are different, yet somehow come together cohesively. The result is a 1/1 garment. About 90% of each pant was used, leaving very little waste. Pocket placement inspired by Katharine Hamnett AW1986 jacket.",
      },
      {
        title: "Space-Ready Pillow Bag",
        details: [
          "Design",
          "Material/ Parts Selection",
          "Patterning",
          "Sewing",
        ],
        processImages: [],
        images: ["sewing/Space-Ready Pillow Side bag/Pillow_bag_1.jpg"],
        description:
          "A bag made for my best friend. I tried something new by using a translucent nylon with pillow stuffing in between layer. Sewing lines on the padding created a protective and comfortable bag.",
      },
      {
        title: "Honda Bomber Hoodie",
        details: ["Design", "Material/ Parts Selection", "Sewing"],
        processImages: [],
        images: ["sewing/Honda Bomber Hoodie/honda_bomber_hoodie_main.jpg"],
        description:
          "This hoodie was an exploration in using found materials. I used my favorite hoodie from my childhood, a red Honda Racing hoodie, along with a bomber jacket to create a new hoodie that I would actually get wear out of.",
      },
      {
        title: "Torso Bag",
        details: [
          "Design",
          "Material/ Parts Selection",
          "Patterning",
          "Sewing",
        ],
        processImages: [],
        images: ["sewing/Torso bag/torso_bag_main.jpg"],
        description: [
          "Inspired by early 90s Prada and Miu Miu bags, this side bag was an experiment in a new type of pattern cutting for me. The goal was to make a bag that conforms to my body and can be worn under a coat rather than on top of one.",
          "Made out of an old pair of pants.",
        ],
      },
      {
        title: "Paint Brush Holder",
        details: [
          "Design",
          "Material/ Parts Selection",
          "Patterning",
          "Sewing",
        ],
        processImages: [],
        images: ["sewing/Paint brush holder/paint_brush_holder_main.jpg"],
        description:
          "Made to hold twelve of my most used paint brushes. It was meant to not only protext my brushes but also give me a simple grab and go solution for when I need to take my brushes somewhere and I don’t want the bristles to get ruined in my backpack.",
      },
      {
        title: "Arch/E Texture Hoodie",
        details: ["Design", "Material/ Parts Selection", "Sewing"],
        processImages: [],
        images: ["sewing/Arch_E Texture Hoodie/Arch-E_front.jpg"],
        description:
          "An exploration in taking two hoodies I no longer wore anymore and combining them into something new that I would get use out of.",
      },
      {
        title: "Utility Shorts",
        details: [
          "Design",
          "Material/ Parts Selection",
          "Patterning",
          "Sewing",
        ],
        processImages: [],
        images: ["sewing/Utility Shorts/utility_shorts_front-min.jpg"],
        description:
          "My first experiment with patterning a pair of shorts. My goal was to make a pair of lightweight, everyday shorts. I patterned the shorts in accordance to my own body measurements.",
      },
      {
        title: "Hiker Pants",
        details: [
          "Design",
          "Material/ Parts Selection",
          "Patterning",
          "Sewing",
        ],
        processImages: [],
        images: ["sewing/Hiker Pants/hiker_pants_main.jpg"],
        description:
          "My first exploration in patterning and making pants from scratch. Patterning took many iterations and multiple muslin protoypes, but this was born out of it. Grey metallic polyester with the back side of green nylon for the pockets and details. ",
      },
      {
        title: "Czech Winter Coat",
        details: ["Design", "Material/ Parts Selection", "Sewing"],
        processImages: [],
        images: ["sewing/Czech Winter Coat/czech_winter_coat_main.jpg"],
        description:
          "When I can, I try my best to not buy new fabric. For this project, I started out with an old Woolrich winter coat that I thrifted. I cropped it, modified the pockets a little bit, and then added a graphic from a vintage T-shirt. My Dad bought this shirt for my Mom when he visited the Czech Republic more than 20 years ago.",
      },
    ],
  },
  {
    title: "Photography",
    type: "gallery_view",
    images: [
      "photography/1_kunio_maekawa.jpg",
      "photography/2_children_at_play.JPG",
      "photography/3_matty_grafitti_portrait.jpg",
      "photography/4_rem_koolhaas_berlin.jpg",
      "photography/5_jenny_caution-min.jpg",
      "photography/6_garrett_808.jpg",
      "photography/7_safin_gg_train.jpg",
      "photography/8_mikuto_fade.JPG",
      "photography/9_mikuto_doubleexp.jpg",
      "photography/10_tokyo_meet_red_white.jpg",
      "photography/11_cole_tent.jpg",
      "photography/12_mikuto_mirror.JPG",
      "photography/13_safin_ICA_smoke-min.jpg",
      "photography/14_yutenji_escalator_VISION.JPG",
      "photography/15_dresden_theatre.jpg",
      "photography/16_passive_aggressive_youth-min.jpg",
      "photography/17_bread_machine.jpg",
      "photography/18_aaron_sevag_rock.jpg",
      "photography/19_spaceship_joshuat.jpg",
      "photography/20_dresden_halfhalf.jpg",
      "photography/21_safin_behind_booth.jpg",
      "photography/22_matty_portrait.jpg",
      "photography/23_matheus_rome.jpg",
      "photography/24_willie_synth.jpg",
      "photography/25_chaos_disorder.jpg",
      "photography/26_crane_warren.jpg",
      "photography/27_kacper_guitar.jpg",
      "photography/28_Mikuto_mexicanbar.JPG",
      "photography/29_spikeball.jpg",
      "photography/30_gg_blue.jpg",
      "photography/31_aaron_boot.jpg",
      "photography/32_team_lab_portrait.jpg",
      "photography/33_Mel_ICA_behind.jpg",
      "photography/34_bundestag.jpg",
      "photography/35_club_group.jpg",
      "photography/36_yuiko_blur.JPG",
      "photography/37_aaron_cole_beach.jpg",
      "photography/38_ICA_day_group-min.jpg",
      "photography/39_brutal_217.jpg",
      "photography/40_berlin_color.jpg",
      "photography/41_ivan_club.jpg",
      "photography/42_J_formation.JPG",
      "photography/43_safin_gg_doubleexp.jpg",
      "photography/44_crane_dresden.jpg",
      "photography/45_sevag_sza.jpg",
      "photography/46_nakameguro_girls.JPG",
    ],
  },
  {
    title: "Engineering",
    type: "item_view",
    items: [
      {
        title: "Custom Motorcycle",
        details: [
          "Design",
          "Research and Development",
          "Parts Selection",
          "Building",
        ],
        images: ["engineering/Motorcycle/motorcycle_MAIN.jpg"],
        processImages: [],
        description:
          "Built from the ground up, this project was years in the making. I started the project when I was 16 to have something to do during the summer and because I loved motorcycles and engineering. I did everything from research and parts selection, to hand sanding every component. ",
      },
      {
        title: "Robot 2017",
        details: ["Team Captain", "Lead Mechanical Designer"],
        images: ["engineering/Robot 2017/robot2017_main.jpg"],
        processImages: [],
        description:
          "Made during my first year as co-captain of the team, this robot implements a lot of new design philosophies for our team. A major goal of mine was to introduce new design and building standards so that the next generations of the team could have a standardized starting point for the following robots. ",
      },
      {
        title: "Robot 2018",
        details: ["Team Captain", "Lead Mechanical Designer"],
        images: ["engineering/Robot 2018/robot2018_pits.jpg"],
        processImages: [],
        description:
          "The team’s most ambitious robot design till this point, this robot pushed the possibilites of what our team was capable of. We implemented a cascading elevaor design, which allows the entire elevator to proportionally move up with the carriage holding the shooting/feeding mechanism. ",
      },
    ],
  },
  {
    title: "Drawing",
    type: "gallery_view",
    images: [
      "drawing/silver_girl.jpg",
      "drawing/black_box_hand.jpg",
      "drawing/christian_bale.jpg",
      "drawing/jonas_dark.jpg",
      "drawing/cowboy.jpg",
      "drawing/frank_ocean.jpg",
      "drawing/winged_victory.jpg",
      "drawing/michelangelo_study.jpg",
      "drawing/pharell.jpg",
      "drawing/solarized_eyes.jpg",
      "drawing/squigly_girl.jpg",
      "drawing/UNITY.jpg",
      "drawing/wassily_chair_girl.jpg",
    ],
  },
];

export const defaultItem = {
  title: "As of Nineteen",
  details: [
    "Oil on canvas, oil and paint marker on plywood, 2x4 wood",
    '28" x 20" x 18"',
  ],
  processImages: [],
  images: ["painting/DSC00008.jpg"],
  description: "This is the description for this piece.",
};

export const aboutImage = "photos/about/about_main.jpg";

export const inspoImages = [
  "inspo/arecibo.jpg",
  "inspo/bjork_margiela.jpg",
  "inspo/bon_iver_studio.jpg",
  "inspo/braun_nizo.jpg",
  "inspo/turrell.jpg",
  "inspo/brutal_stairs.jpg",
  "inspo/calder_car.jpg",
  "inspo/calder_studio.jpg",
  "inspo/chairs.jpg",
  "inspo/chalayan.jpg",
  "inspo/cig_woman.jpg",
  "inspo/clear_nikon.jpg",
  "inspo/crane_dresden.jpg",
  "inspo/ding_helmets.jpg",
  "inspo/donald_judd.jpg",
  "inspo/frankfurt_airport.jpg",
  "inspo/jean_prouve.jpg",
  "inspo/yohji_ithink.jpg",
  "inspo/kanye_truck.jpg",
  "inspo/kiko_dots.jpg",
  "inspo/lemodulor.jpg",
  "inspo/margiela_codes.jpg",
  "inspo/metalchair.jpg",
  "inspo/moholy_nagy.jpg",
  "inspo/motorcycle.jpg",
  "inspo/newbalance_novacancy.jpg",
  "inspo/orange_brutalism.jpg",
  "inspo/veilance_christo.jpg",
  "inspo/portal_spikey.jpg",
  "inspo/record_player.jpg",
  "inspo/red_yellow_moto.jpg",
  "inspo/ron_arad_chair.jpg",
  "inspo/salomon_solar.jpg",
  "inspo/seam_taping_machine.jpg",
  "inspo/senna_monaco.jpg",
  "inspo/uniqlo_handle.jpg",
  "inspo/veilance_mesh.jpg",
];
